### PR TITLE
Added endnotes, preface, and introductions.

### PR DESCRIPTION
**Pull request by thewchan**

### CODE REVIEW

**Comment by acabal** [comment]
This is great work, thanks Matt.

Some notes:

- `e-book` should be `ebook`
- `<cite>` generally does not belong in inline text because it has no context to point to. You can just remove those.
- Spelling: The ebook is `Tao Te Ching` and the author is `Laozi`. However inside the book we have `Tao Tê Ching` and `Lao-Tzŭ`. Should instances inside the book to match?
- I see instances of `Lieh-tzŭ`. Is that a typo?
- Endnote 4, `The sixth chapter of Lao-tzŭ treatise` looks like a typo
- Translator's intro 2: large numbers don't have commas: `5000`, `6000`, and more
- Don't forget to add yourself to the metadata

**Comment by thewchan** [comment]
Thanks @acabal 
e-book -> ebook: I will make the correction
<cite>: Can you clarify when this tag is needed? I basically used it every time something is is "cited", but I think I misunderstood its usage
Tao Te Ching/Laozi: This is a great question; Tao Tê Ching is the proper Wade Giles rendering, Tao Te Ching isn't strictly correct. Laozi is Pinyin, and Lao-tzŭ is the correct Wade Giles rendering. I'm okay either way if we want to make them consistent, just let me know what you'd prefer.
Lieh-tzŭ: Yes he is a different person who also wrote a book that was named after himself; not the same as Lao-tzŭ 
Endnote 4: Yes missing "'s" there, I'll mix that
Numbers: I will correct those
Metadata: What should I be listed?

**Comment by acabal** [comment]
In SE `<cite>` is used to denote the source of its parent element. That usually means a blockquote or something like an endnote. `<cite>` only makes semantic sense if there's a context to look at; if we have 20 cites in one `<p>`, then they are no longer semantically meaningful because what are they referring to? 

Re. title, when I first produced this I went off of the Wikipedia article, which uses `Tao Te Ching` and `Laozi` predominantly. Let's switch the text to match those, just for consistency; you can also put an endnote on the first instance to clarify that for readers. You can use `se reorder-endnotes` to push all the endnotes up by 1 to make room for a new one.

You can list yourself as transcriber and markup in the metadata. Thanks!

**Comment by thewchan** [comment]
@acabal Okay I've addressed the issues. Let me know if you need other things. Thanks!

**Comment by acabal** [comment]
Excellent work, thanks!

**Pull request merged**
